export const APP_ROUTE_NAMES = Object.freeze({
    DASHBOARD: '/',
    BOOKS: 'books',
    CREATE_BOOK: 'create-book',
    EDIT_BOOK: 'edit-book',
    BOOK_STOCK: 'book-stock',
    BOOK_COPIES: 'book-copies',
    CREATE_BOOK_COPY: 'create-book-copy',
    EDIT_BOOK_COPY: 'edit-book-copy',
    BORROW_BOOK: 'borrow-book',
    MY_BOOKS: 'my-books',
    USERS: 'users',
    SIGN_IN: 'sign-in',   
    SIGN_UP: 'sign-up',
    NO_ACCESSS: 'no-access',
    NOT_FOUND: 'not-found',
})